apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        volumeMounts:
        - name: wp-config
          mountPath: /var/www/wordpress/wp-config.php
        - name: wp-nginx-vhost-conf
          mountPath: /etc/nginx/conf.d/
        - name: wordpress-pv-storage
          mountPath: /var/www/wordpress
      volumes:
      - name: wp-config
        configMap:
          name: wordpress-config
          items:
          - key: wp-config.php
            path: wp-config.php
      - name: wp-nginx-vhost-conf
        configMap:
          name: wordpress-config
          items:
          - key: wp-vhost.conf
            path: default.conf
      - name: wordpress-pv-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 5050
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define( 'DB_NAME', 'wordpress' );
    define( 'DB_USER', 'admin' );
    define( 'DB_PASSWORD', 'admin' );
    define( 'DB_HOST', 'mysql' );
    define( 'DB_CHARSET', 'utf8mb4' );
    define( 'DB_COLLATE', '' );
    
    define('AUTH_KEY',         '6yTp#`?Z5[gd`sYV>S+O-mbZ#IW-:p;bWY95 3nTu|d=Y3/db>n=r}2I59s|*-[l');
    define('SECURE_AUTH_KEY',  'l]Et Sz|L7yPzBHq2T%Uq3IcWPp08;GN:l2>lsOCUXd~tJKIB$~?6/^$*M-U~7_<');
    define('LOGGED_IN_KEY',    'fT2[ATB0b/$}2Mnts73-V=iN-e-*FpFB%P-||a/9|=CF>UhZ(kdtJzKaQCPfW|sw');
    define('NONCE_KEY',        'cbj+^)Yq&_ 8vP`Bhf7pgYDB7}l*L(}^*$RdwTFiRK4^[@Yh@|a|uu0LGUu)>ne2');
    define('AUTH_SALT',        '6~f~6++*XDe|`elvncg3,{vYN*9Dd%k+b:8HGOe+rv6ul/3y<c/0+,{tiRX!5su^');
    define('SECURE_AUTH_SALT', 'J>n{Et {z^XVJr8(ti[fii9*</#<_ 0ZS|+W{No)kE/f|+s=M0y8f]0aFe~R+:hf');
    define('LOGGED_IN_SALT',   'H}@D!y2%Tfz(Ytd$:pUp]iz`&SQmI!Y}U3ORLjijdHd=ox,j3$Vh9]/vS-](0MF=');
    define('NONCE_SALT',       ':0Wu%>cjPJ|b4{TSuGwCk%K~nQ@qNbo3y-f|cp$ay~2M+qrJN-_n#-!7( +IW!j<');

    $table_prefix = 'wp_';
    
    define( 'WP_DEBUG', false );
    if ( ! defined( 'ABSPATH' ) ) {
    	define( 'ABSPATH', __DIR__ . '/' );
    }
    require_once ABSPATH . 'wp-settings.php';
  wp-vhost.conf: |
    upstream php {
      server unix:/tmp/php-cgi.socket;
      server 127.0.0.1:9000;
    }
    server {
      server_name _;
      root /var/www/wordpress;
      index index.php;
      location = /favicon.ico {
        log_not_found off;
        access_log off;
      }
      location / {
        try_files $uri $uri/ /index.php?$args;
      }
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
      location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
stringData:
  username: admin
  password: admin