apiVersion: v1
kind: ConfigMap
metadata:
  name: ftps-config
data:
  vsftpd.conf: |
    anonymous_enable=NO
    local_enable=YES
    write_enable=YES
    local_umask=022
    dirmessage_enable=YES
    xferlog_enable=YES
    connect_from_port_20=YES
    vsftpd_log_file=/proc/1/fd/1
    ssl_enable=YES
    listen=YES
    pasv_enable=YES
    pasv_promiscuous=YES
    pasv_min_port=31000
    pasv_max_port=31000
    seccomp_sandbox=NO
    background=NO
    rsa_cert_file=/etc/ssl/certs/vsftpd.crt
    rsa_private_key_file=/etc/ssl/private/vsftpd.key
    ssl_enable=YES
    allow_anon_ssl=NO
    force_local_data_ssl=YES
    force_local_logins_ssl=YES
    ssl_tlsv1=YES
    ssl_sslv2=NO
    ssl_sslv3=NO
    ssl_ciphers=HIGH
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-services
        imagePullPolicy: Never
        ports:
        - name: ftps-data
          containerPort: 20
        - name: ftps-connection
          containerPort: 21
        - name: passv-mode
          containerPort: 30000
        volumeMounts:
        - name: ftps-config
          mountPath: /etc/vsftpd/
      volumes:
        - name: ftps-config
          configMap:
            name: ftps-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  ports:
  - name: ftps-data
    port: 20
  - name: ftps-connection
    port: 21
  - name: passv-mode
    port: 30000
  selector:
    app: ftps
  type: LoadBalancer